import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import { initApiLayer } from "@/lib/api/init";
import { Providers } from "@/providers";
import "./globals.css";

export const lexendDeca = Lexend_Deca({
  subsets: ["latin"], // Specify the desired subsets
  display: "swap", // Recommended for better performance
  variable: "--font-lexend-deca", // Optional: Define a CSS variable for easier styling
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  initApiLayer();

  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
